import { useState, useRef, useEffect } from "react";
import { useCanvasStore, type AtelierExport } from "../stores/canvas-store";
import { sendFeedback } from "../utils/feedback";
import { debugLog } from "../utils/debug";
import { AtelierLogo } from "./AtelierLogo";

export function TopBar({ onOpenComponents, onBackToLibrary }: { onOpenComponents?: () => void; onBackToLibrary?: () => void }) {
  const { project, screens, selectedScreenId, whyMode, toggleWhyMode } = useCanvasStore();
  const [exportOpen, setExportOpen] = useState(false);
  const [copied, setCopied] = useState<string | null>(null);
  const [testLoaded, setTestLoaded] = useState(() =>
    screens.some(s => s.id.startsWith("test_fixture_"))
  );

  const importInputRef = useRef<HTMLInputElement>(null);

  const target = selectedScreenId ? screens.find(s => s.id === selectedScreenId) : null;
  const toExport = target ? [target] : screens;

  const previewHtml = () => {
    toExport.forEach(s => {
      const blob = new Blob([s.html], { type: "text/html" });
      const url = URL.createObjectURL(blob);
      window.open(url, "_blank");
      setTimeout(() => URL.revokeObjectURL(url), 60000);
    });
    setExportOpen(false);
  };

  // Cmd+P / Ctrl+P keyboard shortcut for preview
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "p") {
        e.preventDefault();
        if (screens.length > 0) previewHtml();
      }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [screens, selectedScreenId]);

  const downloadHtml = () => {
    toExport.forEach(s => {
      const blob = new Blob([s.html], { type: "text/html" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url; a.download = `${s.prompt.slice(0, 30).replace(/[^a-z0-9]/gi, "-")}.html`;
      a.click(); URL.revokeObjectURL(url);
      sendFeedback(s.projectId, s.id, "exported", { html: s.html });
    });
    setExportOpen(false);
  };

  const copyHtml = async () => {
    const html = toExport.map(s => s.html).join("\n\n<!-- --- -->\n\n");
    await navigator.clipboard.writeText(html);
    setCopied("html");
    setTimeout(() => setCopied(null), 1500);
  };

  const copyForFigma = async () => {
    // Copy a clean summary + HTML that Figma can interpret when pasted
    const summary = toExport.map(s =>
      `Screen: ${s.prompt}\nDevice: ${s.deviceType}\nSize: ${s.width}x${s.height}\n\n${s.html}`
    ).join("\n\n---\n\n");
    await navigator.clipboard.writeText(summary);
    setCopied("figma");
    setTimeout(() => setCopied(null), 1500);
  };

  const exportReactFiles = () => {
    toExport.forEach(s => {
      // Convert HTML to a basic React component wrapper
      const componentName = s.prompt
        .slice(0, 30)
        .replace(/[^a-zA-Z0-9 ]/g, "")
        .split(" ")
        .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
        .join("") || "Screen";

      const tsx = `import React from "react";

/**
 * Generated by Atelier
 * Prompt: "${s.prompt}"
 * Device: ${s.deviceType} (${s.width}x${s.height})
 */
export default function ${componentName}() {
  return (
    <div dangerouslySetInnerHTML={{ __html: \`${s.html.replace(/`/g, "\\`").replace(/\$/g, "\\$")}\` }} />
  );
}
`;
      const blob = new Blob([tsx], { type: "text/typescript" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url; a.download = `${componentName}.tsx`;
      a.click(); URL.revokeObjectURL(url);
    });
    setExportOpen(false);
  };

  const exportFullProject = () => {
    // Download a ZIP-like structure as individual files + an index
    const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${project?.title || "Atelier Project"}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    body { margin: 0; font-family: system-ui, sans-serif; }
    .screen-nav { display: flex; gap: 8px; padding: 16px; background: #111; }
    .screen-nav button { padding: 8px 16px; border-radius: 8px; border: 1px solid #333; background: #1a1a1a; color: #ccc; cursor: pointer; font-size: 13px; }
    .screen-nav button.active { background: #333; color: #fff; border-color: #555; }
    .screen-frame { width: 100%; min-height: calc(100vh - 56px); }
  </style>
</head>
<body>
  <nav class="screen-nav">
${toExport.map((s, i) => `    <button onclick="show(${i})" id="tab${i}">${s.prompt.slice(0, 30)}</button>`).join("\n")}
  </nav>
${toExport.map((s, i) => `  <iframe id="frame${i}" class="screen-frame" style="display:${i === 0 ? "block" : "none"};border:none;" srcdoc="${s.html.replace(/"/g, "&quot;")}"></iframe>`).join("\n")}
  <script>
    function show(idx) {
      document.querySelectorAll('.screen-frame').forEach((f,i) => { f.style.display = i===idx ? 'block' : 'none'; });
      document.querySelectorAll('.screen-nav button').forEach((b,i) => { b.className = i===idx ? 'active' : ''; });
    }
    show(0);
  </script>
</body>
</html>`;

    const blob = new Blob([indexHtml], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${(project?.title || "project").replace(/[^a-z0-9]/gi, "-")}.html`;
    a.click(); URL.revokeObjectURL(url);
    setExportOpen(false);
  };

  const exportAtelierProject = () => {
    useCanvasStore.getState().exportProject();
    setExportOpen(false);
  };

  const handleImportFile = (file: File) => {
    if (!file.name.endsWith(".atelier")) {
      alert("Please select a .atelier file");
      return;
    }
    const reader = new FileReader();
    reader.onload = () => {
      try {
        const data = JSON.parse(reader.result as string) as AtelierExport;
        if (screens.length > 0) {
          const ok = confirm(
            `Import "${data.project.title}"?\n\nThis will replace the current project.\n${data.screens.length} screen${data.screens.length !== 1 ? "s" : ""} will be loaded.`
          );
          if (!ok) return;
        }
        useCanvasStore.getState().importProject(data);
      } catch (e) {
        alert(`Failed to import: ${(e as Error).message}`);
      }
    };
    reader.readAsText(file);
  };

  const share = async () => {
    const text = screens.map(s => `- ${s.prompt} (${s.deviceType})`).join("\n");
    if (navigator.clipboard) {
      await navigator.clipboard.writeText(`Atelier Project: ${project?.title || "Untitled"}\n\nScreens:\n${text}`);
    }
  };

  return (
    <div style={{
      position: "fixed", top: 0, left: 0, right: 0, height: 48, zIndex: 95,
      display: "flex", alignItems: "center", justifyContent: "space-between",
      padding: "0 16px",
      background: "var(--chrome-bg)",
      borderBottom: "1px solid var(--chrome-border)",
    }}>
      {/* Left */}
      <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
        <AtelierLogo size="md" color="#fafafa" onClick={onBackToLibrary} />
        {onBackToLibrary && (
          <div onClick={onBackToLibrary} style={{ display: "flex", alignItems: "center", gap: 4, cursor: "pointer", color: "var(--chrome-text-secondary)", fontSize: 12, fontWeight: 500 }}
            onMouseEnter={e => e.currentTarget.style.color = "var(--chrome-text)"}
            onMouseLeave={e => e.currentTarget.style.color = "var(--chrome-text-secondary)"}
          >
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="15 18 9 12 15 6"/></svg>
            Projects
          </div>
        )}
        <div style={{ width: 1, height: 16, background: "var(--chrome-border)" }} />
        <span style={{ fontSize: 13, fontWeight: 500, color: "var(--chrome-text-secondary)" }}>
          {project?.title || "New Project"}
        </span>
      </div>

      {/* Center */}
      <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
        <TopBarBtn label="Edit selected" icon={
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
            <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/>
            <path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/>
          </svg>
        } disabled={!selectedScreenId} hint={selectedScreenId ? "Switch to Edit tool" : "Select a screen first"}
          onClick={() => { if (selectedScreenId) { useCanvasStore.getState().setTool("edit"); useCanvasStore.getState().setEditingScreen(selectedScreenId); } }} />
        <div style={{ width: 1, height: 16, background: "var(--chrome-border)", margin: "0 4px" }} />
        {import.meta.env.DEV && (
          <button
            onClick={() => {
              if (testLoaded) {
                import("../test-fixtures").then(m => { m.clearTestFixtures(); setTestLoaded(false); });
              } else {
                import("../test-fixtures").then(m => { m.loadTestFixtures(); setTestLoaded(true); });
              }
            }}
            style={{
              padding: "4px 12px", fontSize: 11, borderRadius: 6, border: "none",
              background: testLoaded ? "#ef4444" : "#fbbf24",
              color: testLoaded ? "white" : "#1f2937",
              cursor: "pointer", fontWeight: 600, fontFamily: "inherit",
            }}
            title={testLoaded ? "Remove test screens and design system" : "Load test screens without AI generation"}
          >
            {testLoaded ? "EXIT TEST" : "TEST"}
          </button>
        )}
        <div style={{ width: 1, height: 16, background: "var(--chrome-border)", margin: "0 4px" }} />
        <TopBarBtn label="Clear canvas" icon={
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
            <polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>
          </svg>
        } disabled={screens.length === 0} hint={screens.length > 0 ? "Remove all screens" : "No screens to clear"}
          onClick={() => { if (screens.length > 0 && confirm("Clear all screens?")) { screens.forEach(s => useCanvasStore.getState().removeScreen(s.id)); } }} />
      </div>

      {/* Right */}
      <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
        {/* Why mode toggle */}
        <button onClick={() => { debugLog('why', `Button clicked, current whyMode=${whyMode}`); toggleWhyMode(); }} style={{
          padding: "6px 14px", borderRadius: 8,
          border: whyMode ? "1px solid #a78bfa" : "1px solid var(--chrome-border)",
          background: whyMode ? "rgba(167, 139, 250, 0.15)" : "transparent",
          color: whyMode ? "#a78bfa" : "var(--chrome-text-secondary)",
          cursor: "pointer", fontSize: 13, fontWeight: 600, fontFamily: "inherit",
          display: "flex", alignItems: "center", gap: 6, transition: "all 0.15s",
        }} title="Toggle design rationale overlay — hover sections to see why they were designed this way">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
            <circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><line x1="12" y1="17" x2="12.01" y2="17"/>
          </svg>
          Why
        </button>
        {/* Components browser */}
        <button onClick={onOpenComponents} style={{
          padding: "6px 14px", borderRadius: 8, border: "1px solid var(--chrome-border)",
          background: "transparent", color: "var(--chrome-text-secondary)", cursor: "pointer",
          fontSize: 13, fontWeight: 500, fontFamily: "inherit", display: "flex", alignItems: "center", gap: 6,
          transition: "all 0.15s",
        }}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
            <rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/>
            <rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>
          </svg>
          Components
        </button>
        {/* Export dropdown */}
        <div style={{ position: "relative" }}>
          <button onClick={() => setExportOpen(!exportOpen)} disabled={screens.length === 0}
            title={screens.length === 0 ? "No screens to export" : "Export options"} style={{
            padding: "6px 14px", borderRadius: 8, border: "1px solid var(--chrome-border)",
            background: exportOpen ? "var(--chrome-surface)" : "transparent",
            color: screens.length > 0 ? "var(--chrome-text)" : "var(--chrome-text-muted)",
            cursor: screens.length > 0 ? "pointer" : "default", opacity: screens.length > 0 ? 1 : 0.5,
            fontSize: 13, fontWeight: 500, fontFamily: "inherit",
            display: "flex", alignItems: "center", gap: 6,
          }}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>
            </svg>
            Export
            <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="6 9 12 15 18 9"/>
            </svg>
          </button>

          {exportOpen && (
            <>
              {/* Click-away overlay */}
              <div onClick={() => setExportOpen(false)} style={{ position: "fixed", inset: 0, zIndex: 98 }} />

              <div style={{
                position: "absolute", top: "calc(100% + 6px)", right: 0, zIndex: 99,
                background: "var(--chrome-surface)", border: "1px solid var(--chrome-border)",
                borderRadius: 12, boxShadow: "var(--shadow-lg)", overflow: "hidden",
                minWidth: 220, animation: "fadeUp 0.12s ease",
              }}>
                <div style={{ padding: "8px 12px", borderBottom: "1px solid var(--chrome-border)" }}>
                  <span style={{ fontSize: 11, color: "var(--chrome-text-muted)", fontWeight: 500 }}>
                    {target ? `Exporting: ${target.prompt.slice(0, 25)}...` : `Exporting ${screens.length} screen${screens.length > 1 ? "s" : ""}`}
                  </span>
                </div>

                <div style={{ padding: 4 }}>
                  <ExportOption
                    icon={<><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></>}
                    label="Preview in Tab"
                    desc={`Open in new tab \u2014 ${navigator.platform.includes("Mac") ? "\u2318" : "Ctrl+"}P`}
                    onClick={previewHtml} />

                  <div style={{ height: 1, background: "var(--chrome-border)", margin: "4px 8px" }} />

                  <ExportOption
                    icon={<><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"/><polyline points="13 2 13 9 20 9"/></>}
                    label="Download HTML"
                    desc="Save as .html files"
                    onClick={downloadHtml} />
                  <ExportOption
                    icon={<><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></>}
                    label={copied === "html" ? "Copied!" : "Copy HTML"}
                    desc="Copy source to clipboard"
                    onClick={copyHtml}
                    success={copied === "html"} />
                  <ExportOption
                    icon={<><polygon points="12 2 2 7 12 12 22 7 12 2"/><polyline points="2 17 12 22 22 17"/><polyline points="2 12 12 17 22 12"/></>}
                    label="Download React TSX"
                    desc="Save as React components"
                    onClick={exportReactFiles} />

                  <div style={{ height: 1, background: "var(--chrome-border)", margin: "4px 8px" }} />

                  <ExportOption
                    icon={<><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></>}
                    label="Download full project"
                    desc="All screens in one HTML file"
                    onClick={exportFullProject} />
                  <ExportOption
                    icon={<><rect x="2" y="3" width="20" height="14" rx="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></>}
                    label={copied === "figma" ? "Copied!" : "Copy for Figma"}
                    desc="Copy HTML to paste into Figma"
                    onClick={copyForFigma}
                    success={copied === "figma"} />

                  <div style={{ height: 1, background: "var(--chrome-border)", margin: "4px 8px" }} />

                  <ExportOption
                    icon={<><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><path d="M12 18v-6"/><path d="M9 15l3-3 3 3"/></>}
                    label="Export Project (.atelier)"
                    desc="Save full project for later import"
                    onClick={exportAtelierProject} />
                  <ExportOption
                    icon={<><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></>}
                    label="Import Project (.atelier)"
                    desc="Load a previously exported project"
                    onClick={() => { importInputRef.current?.click(); setExportOpen(false); }} />
                </div>
              </div>
            </>
          )}
        </div>

        {/* Hidden file input for import */}
        <input
          ref={importInputRef}
          type="file"
          accept=".atelier"
          style={{ display: "none" }}
          onChange={(e) => {
            const file = e.target.files?.[0];
            if (file) handleImportFile(file);
            e.target.value = "";
          }}
        />

        {/* Import button — always available */}
        <button onClick={() => importInputRef.current?.click()} title="Import a .atelier project file" style={{
          padding: "6px 14px", borderRadius: 8, border: "1px solid var(--chrome-border)",
          background: "transparent", color: "var(--chrome-text-secondary)", cursor: "pointer",
          fontSize: 13, fontWeight: 500, fontFamily: "inherit",
          display: "flex", alignItems: "center", gap: 6,
        }}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/>
          </svg>
          Import
        </button>

        <button onClick={share} disabled={screens.length === 0} title={screens.length === 0 ? "No screens to share" : "Copy project info to clipboard"} style={{
          padding: "6px 14px", borderRadius: 8, border: "none",
          background: screens.length > 0 ? "var(--chrome-text)" : "var(--chrome-text-muted)",
          color: "var(--chrome-bg)", cursor: screens.length > 0 ? "pointer" : "default",
          opacity: screens.length > 0 ? 1 : 0.5,
          fontSize: 13, fontWeight: 500, fontFamily: "inherit",
          display: "flex", alignItems: "center", gap: 6,
        }}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
            <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"/>
            <polyline points="16 6 12 2 8 6"/><line x1="12" y1="2" x2="12" y2="15"/>
          </svg>
          Share
        </button>
      </div>
    </div>
  );
}

function ExportOption({ icon, label, desc, onClick, success }: {
  icon: React.ReactNode; label: string; desc: string; onClick: () => void; success?: boolean;
}) {
  const [hovered, setHovered] = useState(false);
  return (
    <button onClick={onClick}
      onMouseEnter={() => setHovered(true)} onMouseLeave={() => setHovered(false)}
      style={{
        width: "100%", display: "flex", alignItems: "center", gap: 10,
        padding: "10px 12px", border: "none", borderRadius: 8,
        background: hovered ? "var(--chrome-bg)" : "transparent",
        cursor: "pointer", fontFamily: "inherit", textAlign: "left",
        transition: "background 0.1s",
      }}>
      <span style={{ color: success ? "#22c55e" : "var(--chrome-text-muted)", flexShrink: 0 }}>
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">{icon}</svg>
      </span>
      <div>
        <div style={{ fontSize: 13, fontWeight: 500, color: success ? "#22c55e" : "var(--chrome-text)" }}>{label}</div>
        <div style={{ fontSize: 11, color: "var(--chrome-text-muted)", marginTop: 1 }}>{desc}</div>
      </div>
    </button>
  );
}

function TopBarBtn({ label, icon, disabled, hint, onClick }: { label: string; icon: React.ReactNode; disabled?: boolean; hint?: string; onClick?: () => void }) {
  return (
    <button disabled={disabled} title={hint || label} onClick={onClick} style={{
      padding: "6px 10px", borderRadius: 8, border: "none",
      background: "transparent", color: disabled ? "var(--chrome-text-placeholder)" : "var(--chrome-text-secondary)",
      cursor: disabled ? "default" : "pointer",
      fontSize: 13, fontWeight: 500, fontFamily: "inherit",
      display: "flex", alignItems: "center", gap: 6, opacity: disabled ? 0.5 : 1,
    }}>
      {icon} {label}
    </button>
  );
}
